### ISSUE TITLE
Build failure: Could not find com.android.tools.build:gradle:3.0.1

### ISSUE THREAD

**Issue by relan** [ScreamingHawk/android-slideshow#100]
Hi,

F-Droid maintainer here. Slideshow [fails to build](https://f-droid.org/wiki/page/link.standen.michael.slideshow/lastbuild_41) since 2.2.1:

> Could not resolve all files for configuration ':classpath'.
> Could not find com.android.tools.build:gradle:3.0.1.

Steps to reproduce:

1. `cd app`
2. `gradle assembleRelease`

The problem here is that Android Gradle plugin 3.0.1 is available only in Google Maven repo, not JCenter. Please adjust your [top-level build.gradle](https://developer.android.com/studio/build/index.html#top-level).

**Comment by ScreamingHawk** [comment]
F-Droid has updated their supported versions. This is no longer an issue.

**Comment by relan** [comment]
Actually [this change](https://github.com/ScreamingHawk/android-slideshow/commit/ded6c7b9a00165bc1ff296ef23508d4cc2b8d905#diff-c197962302397baf3a4cc36463dce5eaR6) fixed Slideshow, not F-Droid.
