### ISSUE TITLE
Add support for EXIF orientation

### ISSUE THREAD

**Issue by nmeo** [ScreamingHawk/android-slideshow#101]
Some pictures that have an EXIF orientation tag do not appear to be rotated correctly. It would be nice to add support for this so some pictures don't show up sideways.

**Comment by ScreamingHawk** [comment]
After working on #109 , this one should be pretty easy

**Comment by mettyw** [comment]
Hi, I guess this is still open right? Should there be a separate preference for EXIF orientation support, roughly like this:
* EXIF_ROTATE_DIMEN: "Rotate image according to EXIF tag, if present"
* AUTO_ROTATE_DIMEN: "Rotate image to landscape, if EXIF rotation preference is disabled or no EXIF tag is present"

Or do you think it should be combined in one? I would opt for two separate choices. 

By the way, correct EXIF orientation handling seems not to be so easy: https://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/ (direct link to github repo with test images: https://github.com/recurser/exif-orientation-examples)

**Comment by ScreamingHawk** [comment]
Hey @mettyw. Change your import to use `android.support.media.ExifInterface` as the error message states. You may need to add another support library to the `gradle.properties`. If you are using Android Studio it should recommend the correct one. 

Once you get that squash I'll have it merged in. This is great! Thanks so much for your contributions!!!

**Comment by ScreamingHawk** [comment]
Big thanks to @mettyw for doing all the work on this one!!!
