### ISSUE TITLE
Rotating Phone Restarts Application

### ISSUE THREAD

**Issue by beckysophie** [ScreamingHawk/android-slideshow#114]
***Expected Behavior***

Just like some similar apps, regardless of the orientation, users should be able to use the App without any errors 

***Actual Behavior***

When in a folder of where pictures are stored, and the device orientation goes landscape, it would take users to the root folder and start all over again..... 

***How to produce the bug***

* Open the app 
* Locate and select any folder where images are stored 
* Rotate screen
* It would take you to the root folder where you have to start all over again 

 

***TEST TOOLS***

* Operating system : Android 6.0
* Phone : Infinix hot s
* Slideshow v2.5.0

***Recording of the bug is showned below......***

Watch the video below to see how it behaves.... 

https://youtu.be/JQQi_rgEZB0

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@beckysophie/slideshow-app-goes-to-the-root-folder-unexpectedly">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ScreamingHawk** [comment]
Thanks! I had never noticed this before. It's even more annoying when you've got the auto start setting on.

**Comment by beckysophie** [comment]
You're most welcome

**Comment by SamuelBiros** [comment]
Hey there, it this issue still up for grabs? I would be interested..

**Comment by ScreamingHawk** [comment]
Hi @SamuelBiros Yes it is! Feel free to pick it up. If you need any help you can drop me a message

**Comment by SamuelBiros** [comment]
Hello, the problem is solved. I requested a merge.

**Comment by ScreamingHawk** [comment]
Thanks so much @SamuelBiros 

Sorry it took so long to approve this merge request. It's now included and I'll have a release out shortly: https://github.com/ScreamingHawk/android-slideshow/commit/df58fd5aca1004e0e8e4d6692cc0c2d6b1d32378

**Comment by ScreamingHawk** [comment]
That wasn't shortly at all 😅 I've pushed this through to the beta stream. Will have a play for a while before moving to production. FYI Anyone is able to access the beta stream.
