### ISSUE TITLE
Handle NullPointerException on ImageActivity.loadImage

### ISSUE THREAD

**Issue by ScreamingHawk** [ScreamingHawk/android-slideshow#120]
```
Caused by: java.lang.NullPointerException: 
  at link.standen.michael.slideshow.ImageActivity.loadImage (ImageActivity.java:548)
  at link.standen.michael.slideshow.ImageActivity.onCreate (ImageActivity.java:330)
  at android.app.Activity.performCreate (Activity.java:7090)
```

Untested but this error could possibly occur when the user selects "Play From Here" when there is nothing in the folder. Would be nice if this `NullPointerException` was caught and the user was bounced back to the list view with a toast saying:

> No images found

or similar

**Comment by patm22** [comment]
Hi, can i take it ?

**Comment by ScreamingHawk** [comment]
@patm22 Yes please! I haven't had the chance to properly debug this so you might have trouble testing it.

**Comment by patm22** [comment]
Check for empty list is properly done. I believe that bug is somewhere else however I was not able to reproduce it. 
All I can do is put try catch and check whether NullPointerException occur and if yes show error toast. I already implemented this and I can create pull request, is it going to be okay?

**Comment by ScreamingHawk** [comment]
Sure. Submit a pull request and I'll have a look at the implementation. I wasn't able to replicate the error either. Are you bouncing the user back to the list activity as well as toasting? That would be good enough for this one I think.

**Comment by ScreamingHawk** [comment]
Yeah that'll do. Thanks for this! One of those things that needs to be done but I don't have the time. I'll be sure to add a thanks to the change log when I deploy this one. 

Thanks again!
