### ISSUE TITLE
Option to lock screen

### ISSUE THREAD

**Issue by mettyw** [ScreamingHawk/android-slideshow#131]
It would be great if it would be possible to lock the screen. E.g. if you do a long press on the display, the screen would be locked until you do another long-press. "Locked" means that no input is accepted and no buttons appear.

Rationale: in some usage scenarios the slide show is deployed at "grandma's" who likes to clean the dust from it. During cleaning she might accidentally touch the screen. In order to ensure reliable operation, the aforementioned "lock" feature would be a very cool addition.

Details:
* add option for "lock screen"
* add option whether screen shall be locked on startup or not

**Comment by ScreamingHawk** [comment]
Done! Expect to see this in the next release. I'm a bit behind on releases so will try to get around to making a release this week

**Comment by ScreamingHawk** [comment]
Eh, I just did it now. Enjoy!
