### ISSUE TITLE
Add bookmark or last slideshow

### ISSUE THREAD

**Issue by jacksonjosekunnel** [ScreamingHawk/android-slideshow#145]
Please add a feature to continue last slideshow or add bookmarks or favourites option. Thanks

**Comment by ScreamingHawk** [comment]
This is a cool feature idea. Thanks for the suggestion!

**Comment by ScreamingHawk** [comment]
FYI there is already an option to remember the last location you started a slideshow and another for immediately starting at the last image too. I think that is enough for this ticket
