### ISSUE TITLE
Request: Slideshow from extSdCard and UsbDrive

### ISSUE THREAD

**Issue by Rbagman** [ScreamingHawk/android-slideshow#15]
Request: Slideshow from extSdCard and UsbDrive

**Comment by mobtechpd** [comment]
Yes it will be very nice to run photo slides from external sd or usb drive

**Comment by ScreamingHawk** [comment]
Good idea. None of my devices have external SD cards so it never occurred to me. Will add this to the list of enhancements

**Comment by ScreamingHawk** [comment]
@Rbagman @mobtechpd Do you have a particular device in mind? Will use it for testing.

**Comment by aj664** [comment]
1.  read from external sd card.   is it not just in /mnt/  somewhere?  shouldn't be too hard to add.
2.  delay setting for setting the number of seconds to show each pic
3.  touch pic pause on that one until a left/right swipe starts it again.

**Comment by ScreamingHawk** [comment]
@aj664 It's not a question of how hard it is. Each device can mount the external storage differently and rather than testing all devices with all combinations of cards, I'd rather test the use cases of actual users. 

Points 2 and 3 are unrelated to this ticket. Point 2 is already a feature, check the settings. Point 3, there is already touch to pause, touch to resume and you can swipe to change pic regardless of whether the application are running. I'll add this to the README

**Comment by Rbagman** [comment]
@ScreamingHawk I have a Samsung GT-N7100/Android 4.4.2. Thanks.

**Comment by aj664** [comment]
sorry!  i was directed here from a link that says 'provide  suggestions', i was unaware of the 1 suggestion per comment policy.. and i wanted to list them in order of importance.  
1. hope this helps:  http://stackoverflow.com/questions/11716448/how-to-access-external-micro-sd-card-of-the-phone
2. my bad, i only recalled there being switches in the settings, didn't realize submenus.
3. swipe to advance quicker was what i should have said.

the feature/unfeature list you have on the Android Play store text is awesome.  i think that really helps people looking for exactly this type of app.

**Comment by ScreamingHawk** [comment]
@Rbagman Sweet I'll test with that. Thanks

@aj664 I've created issue #19 for point 3. Further discussion there? Thanks for the request.

**Comment by ScreamingHawk** [comment]
Note to self: http://stackoverflow.com/a/31853303

**Comment by ScreamingHawk** [comment]
Pushed a release to beta on the app store. F-droid should pick it up whenever they refresh their repository (I'm not familiar with how that works). Let me know here if there are any issues. If I don't hear anything after <some period> I'll consider it closed. 

Enjoy! :cat:

**Comment by Rbagman** [comment]
@ScreamingHawk OK. New updates posted this morning. Slideshow wasn't in the batch.

**Comment by aj664** [comment]
I just updated via play store, and the version i got doesn't appear to have any way to access the sdcard..  there is no linux-like root folder structure, and no apparent /mnt folder or anything.   I was unsure of whether i'm seeing this new version or not, so i looked in the About screen, and there is no version number..  maybe a version number would be helpful in identifying if we have got the latest.

my folder indicator says just: /
and then i see folders like  Alarms, Android, DCIM, Documents, Downloads, Movies, Music, Notifications, Ringtones.   and some misc app folders... i don't see any linux-like root folders, no apparent way to go lower to find /mnt/  etc.. 
how would the ext-sdcard appear such that i can access it?

**Comment by ScreamingHawk** [comment]
@aj664 Nuts. Worked my virtual device. Unfortunately I don't have a real device with an SD card. What I'll do instead is allow access from the root directory of the device. This means you'll have to know where your SD card is mounted in order to access it (sounds like you do), but it also means that I can't muck up again. 

This solution is actually a lot easier to code so an update should be pushed shortly.

**Comment by ScreamingHawk** [comment]
ES File Explorer (non-free, bloated, ads) appears to have the same option as I'm implementing in Slideshow (mentioned above) but the root directory and other upper folders appear empty. 

Looks like you'll need to have a rooted device to use this properly?? 

Someone correct me if I'm wrong.

**Comment by ScreamingHawk** [comment]
Beta updated again. Let me know how it goes.

**Comment by aj664** [comment]
improved!  i can get to it.. it works! it works!!    but there is a usability bug..
the app opens at what i'll call the `Android User folders`..  Music,Documents,Ringtones etc..  (so far so good)..  i went into the settings and changed the 'Use Device Root' to on.  i press back, and i go back to the Android User folders (so far so good)..   (minor usability issue here..  the folder indicator at the top shows just "/" which as a regular user seems like you can't go back any further, and if i were to hit the back button again it would exit the app)..  anyway, moving on..   I hit back.. and i get to the  /storage/emulated/  folder that has 2 entries:
  0
  legacy
now we are in the linux-ish folders..  hit back again..  and i see:
  emulated
  external_SD
  sdcard0
  USBstorage1
  USBstorage2
  USBstorage3
   etc..
awesome!!  i can now get to the sdcard!!    

now the problem...   i'm currently at  /storage/
i hit back again..  (cause i ws curious!  and/or i want to exit the app)
it goes back to "/"  (this time the linux fs root, not the Andriod User folders root that is also labelled as "/"
the folder info bar now says "/ (inaccessable)"    ok, so far so good... but there is no folders to go back to..  so i am now stuck.    i hit back (as it's the only thing i can do) and the app exits.  ok, expected that.  when i relaunch the app, im back at this "/ (inaccesable)"  and i can't get out of it.

i had to go into settings turn off the 'Use Root'  that then reset me back to the Android User folders.. then back into the settings and turn 'Use Root'  back on again.

**Comment by Rbagman** [comment]
I'm still waiting on F-Droid. :/

**Comment by ScreamingHawk** [comment]
@Rbagman sorry I have no idea how frequently f-Droid updated their repositories or even if there is something I need to do to update it

@aj664 yay! I'll add some handling in case the user gets lost in an inaccessible folder

**Comment by ScreamingHawk** [comment]
Beta updated again with helper link when you are in an inaccessible folder. This should stop you getting stuck when browsing root folders. Also opening the app starts at the default SD card location instead of device root (when that setting was enabled). 

Can I close this ticket yet? ;)

**Comment by aj664** [comment]
the  'Stuck? Click to go home' worked well.   the startup location works too.  
yep, i think this ticket is done!    thank you.

**Comment by ScreamingHawk** [comment]
Woohoo! Thanks for the help testing this. Hopefully f-droid will update soon
