### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [ScreamingHawk/android-slideshow#152]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by ScreamingHawk** [comment]
Not a bad idea. Will do this when I get a chance

**Comment by mondlicht-und-sterne** [comment]
surely because fastlane is not so easy?
