### ISSUE TITLE
Fix translations

### ISSUE THREAD

**Issue by krt16s** [ScreamingHawk/android-slideshow#21]
Build fails for translation issues. While AS ignores them, they should either be fixed or made non-breaking on your side. E.g. I do:

`echo -e "android { lintOptions { disable 'MissingTranslation'\n\ndisable 'ExtraTranslation' } }" >> app/build.gradle`

**Comment by ScreamingHawk** [comment]
As I'm not fluent in the translated language, I won't be 'fixing' them myself. Have taken your advice with the additional lint options.
