### ISSUE TITLE
Update Play Store Promo Images

### ISSUE THREAD

**Issue by ScreamingHawk** [ScreamingHawk/android-slideshow#24]
The images suck. I want better ones. 

Make a folder in the repository root named `promo_images` and populate as follows:

|Location|Image Count|Size|Type|Description|
|----------|----------|----------|----------|----------|
|`promo_images/Screenshots/Phone/`|2-7|1280×720 or 720x1280|JPEG or 24-bit PNG (no alpha)|Screenshots of the application on a phone|
|`promo_images/Screenshots/Tablet/`|2-7|1280×720 or 720x1280|JPEG or 24-bit PNG (no alpha)|Screenshots of the application on a tablet (7 inch **and** 10 inch)|
|`promo_images/Hi-res_Icon/`|1|512x512|32-bit PNG (with alpha)|High resolution image of the icon|
|`promo_images/Feature_Graphic/`|1|1024x500|JPG or 24-bit PNG (no alpha)|Image for the banner on the Play Store|
|`promo_images/Promo_Graphic/`|1|180x120|JPG or 24-bit PNG (no alpha)|No idea where this is used (Optional)|

**Comment by ScreamingHawk** [comment]
When taking screenshots of images please ensure the images aren't subject to copyright. https://unsplash.com/ is a fantastic resource for free public domain images.

**Comment by jcampos187** [comment]
Hello do you still need help with this?

**Comment by ScreamingHawk** [comment]
@jcampos187 Yes please! Let me know if you have any questions. App can be downloaded from the Play Store of F-droid. Or you can run the code in an emulator through Android Studio. 

Thanks

**Comment by psyanite** [comment]
This article talks about the Promo Graphic:
https://support.google.com/googleplay/android-developer/answer/1078870?hl=en

Maybe displayed on the market like in this article:
https://android-developers.googleblog.com/2011/10/android-market-featured-image.html

**Comment by ScreamingHawk** [comment]
Couple of the images requested have been supplied. Thanks to @psyanite. Still need some good screenshots

**Comment by ScreamingHawk** [comment]
I just gave up on this one 😂
