### ISSUE TITLE
Change Log

### ISSUE THREAD

**Issue by ScreamingHawk** [ScreamingHawk/android-slideshow#71]
This application changes a lot. Should have a change log.

**Comment by ScreamingHawk** [comment]
I'm thinking about the best way to implement this while keeping in mind that the translations are not updated as frequently as the application. The chances are high that the change log will never be translated on time or translated at a previous version and remain out of date. 

I want the change log to appear when the app is first loaded, showing the recent changes, then store a `SharedPreference` so it doesn't pop up until a new version. 

Given this will be the first thing a user will see when using the application, it would be off putting for users other non-English languages to be bombarded with English text. 

Including a setting to remove change log notifications will help. Also add a translated message with something like:

> To disable Change Log notifications, visit the settings. 

But this won't fix the initial impression for new non-English users. 

I don't want change log notifications to be off by default, or no one will see them. Might change my opinion on this if I can't think of a better alternative. 

**Potential alternative**: Change log notification setting defaults to true for English language, false otherwise.

**Comment by DaricusDuncan** [comment]
@ScreamingHawk  Is this project open for volunteers that are still learning Java and Android Studio?

**Comment by ScreamingHawk** [comment]
@DaricusDuncan absolutely! Feel free to submit a pull request and don't be afraid to ask for help if you need it :)

**Comment by ScreamingHawk** [comment]
I've used this plugin in another app (https://github.com/ScreamingHawk/phone-saver) and it seems to work really well: https://github.com/cketti/ckChangeLog

**Comment by DaricusDuncan** [comment]
@ScreamingHawk Just wanted to check in and let you know that I am still working on this and reviewing all of the information you have provided. Thank you so much for the help!

**Comment by ScreamingHawk** [comment]
Thanks @DaricusDuncan! Don't hesitate to ask for advice if you need help.

**Comment by ScreamingHawk** [comment]
And I'm happy to populate the change log with the release messages myself. No need for you to do that :)

**Comment by DaricusDuncan** [comment]
@ScreamingHawk  I completely understand. I had to take a step back and really get a deep understanding of Java and how everything is working so I have been busy learning Java basically man.

**Comment by ScreamingHawk** [comment]
Added change log. 

Change log only displays when selected from the menu for non English users. 
For English, the change log also opens when a new version is detected showing only the changes.
