### ISSUE TITLE
Tag for v2.2.0 missing

### ISSUE THREAD

**Issue by Bubu** [ScreamingHawk/android-slideshow#87]
For the F-droid build to be able to effectively upgrade to newer version it would be helpful if you could add the tag for the 2.2.0 release (and then for the following versions).

The new versions will than be automatically picked up, build and diustributed shortly after you add the new tag.

The tag should always correspond to the version name, i.e. tagging version 2.2.0 as v2.2.0.

**Comment by ScreamingHawk** [comment]
Oops! Thanks for noticing! 

I've added `--follow-tags` to my `git config` so this shouldn't get missed again.
